### ISSUE TITLE
mkdocstrings-twincat handler usage example

### ISSUE THREAD

**Issue by philippleidig** [drehstromer/mkdocstrings-twincat#1]
I try to use the mkdocs plugin or mkdocstrings handler, but fail after several attempts with the same error message.

`ERROR   -  Error reading page 'index.md': No module named 'mkdocstrings_handlers.python'`

Packages `mkdocstrings` and `mkdocstrings-twincat` are successfully installed.
Are there any instructions on how to use the handler? 😇

mkdocs.yml
```yml
plugins:
  - mkdocstrings:
      handlers:
        twincat:
          options:
            show_signature: true
            show_source: true
      default_handler: null 
```

index.md
```md
::: twincat
    path: FB_Axis.TcPOU
    show_signature: true
    show_source: true
```

Thanks for the help 🙂
